- name: Generate var file for order_svc.sh script
  template:
    src: aws_jq_vars.yml
    dest: /tmp/aws_jq_vars.yml

- name: Generate var file for tower module
  template:
    src: tower_info.yml
    dest: /tmp/tower_info.yml

- name: Copy opentlc ssh keys
  copy:
    src: /root/.ssh/openstack.pub
    dest: /root/.ssh/openstack.pub


- name: Copy inventory vars
  copy:
    src: inventory_vars.json
    dest: /root/inventory_vars.json
